version: "3.8"

services:
  redis_db:
    image: "redis:alpine"
    container_name: redis_db
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app_network

  app:
    build: ./app
    container_name: websocket_app
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis_db}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CLIENT_URL=${CLIENT_URL:-http://localhost}
      - PORT=${PORT:-3000}
    env_file:
      - .env
    depends_on:
      - redis_db
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./html:/usr/share/nginx/html
    ports:
      - "${NGINX_PORT_HTTP:-80}:80"
      - "${NGINX_PORT_HTTPS:-443}:443"
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
