version: "3.8"

services:
  redis_db:
    image: "redis:alpine"
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - redis_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
